#!/usr/bin/env groovy

properties([
    disableConcurrentBuilds(),
    pipelineTriggers([cron('H 5 * * *')]),
])

podTemplate(label: 'jenkins-slave', containers: [
    containerTemplate(name: 'docker', image: 'docker:latest', command: 'cat', ttyEnabled: true),
],
volumes:[
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
]) {
    ansiColor('xterm') {
        timeout(time: 10, unit: 'MINUTES') {
            node ('jenkins-slave') {
                stage('Cleaning') {
                    container('docker') {
                        sh "docker images"
                        sh "docker system prune -af"
                        sh "docker images"
                    }
                }
            }
        }
    }
}
