#!/usr/bin/env groovy

properties([
    disableConcurrentBuilds(),
    pipelineTriggers([cron('H 5 * * *')]),
])

podTemplate(label: 'jenkins-slave-docker', containers: [
    containerTemplate(name: 'jnlp', image: 'jenkins/jnlp-slave:latest-jdk11',
                        args: '${computer.jnlpmac} ${computer.name}', workingDir: '/home/jenkins',
                        resourceRequestCpu: '200m', resourceLimitCpu: '300m',
                        resourceRequestMemory: '256Mi', resourceLimitMemory: '512Mi'),
    containerTemplate(name: 'docker', image: 'docker:latest', command: 'cat', ttyEnabled: true),
],
volumes:[
    hostPathVolume(mountPath: '/var/run/docker.sock', hostPath: '/var/run/docker.sock'),
]) {
    ansiColor('xterm') {
        node ('jenkins-slave-docker') {
            stage('Cleaning') {
                container('docker') {
                    sh "docker images"
                    sh "docker system prune -af"
                    sh "docker images"
                }
            }
        }
    }
}
