apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "s3fs.fullname" . }}
  labels:
    app: s3fs
    app.kubernetes.io/name: {{ include "s3fs.name" . }}
    helm.sh/chart: {{ include "s3fs.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: s3fs
      app.kubernetes.io/name: {{ include "s3fs.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: s3fs
        tier: storage
        app.kubernetes.io/name: {{ include "s3fs.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            privileged: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: S3_BUCKET
            value: {{ .Values.environment.bucket }}
          - name: S3_REGION
            value: {{ .Values.environment.region }}
          - name: MNT_POINT
            value: {{ .Values.environment.mntpoint }}
          - name: AWS_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.environment.secretKeyRef }}
                key: aws_accesskey
          - name: AWS_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: {{ .Values.environment.secretKeyRef }}
                key: aws_secretkey
          volumeMounts:
          - name: devfuse
            mountPath: /dev/fuse
          - name: sharedfs
            mountPath: {{ .Values.environment.mntpoint }}:shared
      terminationGracePeriodSeconds: 30
      volumes:
      - name: devfuse
        hostPath:
          path: /dev/fuse
      - name: sharedfs
        hostPath:
          path: /{{ .Values.environment.bucket }}
