# Default values for my-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: AWSID.dkr.ecr.REGION.amazonaws.com/REPO
  flag: test
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths:
    - ""
  port: 80
  hosts:
    - my-app.test.domain.net
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

environment:
  secretKeyRef: mysql-testdb-secret
  mysql_database: drupal8
  mysql_host: mysql-testdb.test.domain.net
  mysql_port: 3306

#probes: # liveness, readiness
#  path: /ping
#  port: http

volume:
  testdb:
    mountPath: /var/run/mysqld

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
